(function(){
'use strict';
var KEY='recorrida_confinamento_v1',state=load(),selectedKey='',selected=new Set();
function defaults(){return {version:1,reportDate:'',importedAt:'',lots:[],notes:[]};}
function load(){try{var d=JSON.parse(localStorage.getItem(KEY));if(d&&Array.isArray(d.lots)&&Array.isArray(d.notes))return Object.assign(defaults(),d);}catch(e){}return defaults();}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function el(id){return document.getElementById(id);}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim().toUpperCase();}
function number(v){var x=parseFloat(String(v||'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));return isFinite(x)?x:0;}
function inputNumber(v){var s=String(v==null?'':v).trim();if(!s)return null;s=s.replace(/\s/g,'');if(s.indexOf(',')>=0)s=s.replace(/\./g,'').replace(',','.');var x=parseFloat(s.replace(/[^0-9.-]/g,''));return isFinite(x)?x:null;}
function int(v){return Math.round(Number(v)||0).toLocaleString('pt-BR');}
function decimal(v,d){return Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});}
function dateIso(v){var p=String(v).split('/');return p.length===3?p[2]+'-'+p[1].padStart(2,'0')+'-'+p[0].padStart(2,'0'):'';}
function partialDateIso(dd,mm,yy,reportDateIso){dd=dd.padStart(2,'0');mm=mm.padStart(2,'0');var year;if(yy.length>=4){year=yy.slice(0,4);}else if(reportDateIso){var refYear=Number(reportDateIso.slice(0,4)),refMonth=Number(reportDateIso.slice(5,7));year=String(Number(mm)<=refMonth?refYear:refYear-1);}else{year=String(new Date().getFullYear());}return year+'-'+mm+'-'+dd;}
function dateBr(v){if(!v)return '—';var p=v.split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:v;}
function pad2(n){return String(n).padStart(2,'0');}
function tsFile(d){return d.getFullYear()+'-'+pad2(d.getMonth()+1)+'-'+pad2(d.getDate())+'_'+pad2(d.getHours())+'-'+pad2(d.getMinutes())+'-'+pad2(d.getSeconds());}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7);}
function lotKey(l){return norm(l.name)+'|'+String(l.entryDate||'');}
function activeNotes(l){var lk=lotKey(l);return state.notes.filter(function(n){return n.status==='active'&&((n.scope==='lot'&&n.targetKey===lk)||(n.scope==='pen'&&n.targetKey===l.pen));});}
function showToast(msg){var t=el('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(function(){t.classList.remove('show');},2800);}
function textRange(row,min,max){return row.filter(function(i){return i.x>=min&&i.x<max;}).map(function(i){return i.text;}).join(' ').trim();}
function nearbyDiet(clean,y){return clean.filter(function(i){var x=i.transform[4],dy=i.transform[5]-y,t=String(i.str||'').trim();return x>=340&&x<412&&dy>=-13&&dy<=13&&t&&!/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(t);}).sort(function(a,b){var dd=b.transform[5]-a.transform[5];return Math.abs(dd)>2?dd:a.transform[4]-b.transform[4];}).map(function(i){return String(i.str).trim();}).join(' ').trim();}
function parsePage(items,context){
  var clean=items.filter(function(i){return String(i.str||'').trim();}),groups={};
  clean.forEach(function(i){var y=Math.round(i.transform[5]/2)*2;(groups[y]||(groups[y]=[])).push({x:i.transform[4],text:String(i.str).trim()});});
  var all=clean.slice().sort(function(a,b){var d=b.transform[5]-a.transform[5];return Math.abs(d)>2?d:a.transform[4]-b.transform[4];}).map(function(i){return String(i.str).trim();}).join(' '),rm=all.match(/Data\s+de\s+refer[^:]*:\s*(\d{1,2}\/\d{1,2}\/\d{4})/i);
  if(rm){context.reportDate=dateIso(rm[1]);}
  var out=[];Object.keys(groups).map(Number).sort(function(a,b){return b-a;}).forEach(function(y){var row=groups[y].sort(function(a,b){return a.x-b.x;}),joined=row.map(function(i){return i.text;}).join(' '),lm=joined.match(/Linha:\s*(?:LINHA\s*)?(PASTO|[A-P])\b/i);if(lm){context.line=lm[1].toUpperCase();return;}if(context.line==='PASTO'||/Subtotal/i.test(joined))return;
    var name=textRange(row,35,88);if(!/^(LOTE|ENFERMARIA)\b/i.test(name))return;var pen=textRange(row,88,120).replace(/\s+/g,' ').trim(),qty=parseInt(textRange(row,120,152).replace(/\D/g,''),10)||0,line=((pen.match(/^([A-P])\b/i)||[])[1]||context.line||'').toUpperCase();if(!qty||!line)return;
    var entryText=textRange(row,443,486),entryMatch=entryText.match(/(\d{1,2})\/(\d{1,2})\/(\d{2,4})/),exitText=textRange(row,632,680),exitMatch=exitText.match(/\d{1,2}\/\d{1,2}\/\d{4}/),rawType=textRange(row,298,340),own=/^ANIMAIS?/i.test(norm(rawType));
    out.push({name:name,pen:pen,line:line,quantity:qty,deaths:parseInt(textRange(row,152,178).replace(/\D/g,''),10)||0,breed:textRange(row,196,236),category:textRange(row,236,296),rawType:rawType,type:own?'own':'boitel',diet:nearbyDiet(clean,y)||'NÃO INFORMADA',entryDate:entryMatch?partialDateIso(entryMatch[1],entryMatch[2],entryMatch[3],context.reportDate):'',days:parseInt(textRange(row,486,512).replace(/\D/g,''),10)||0,treatmentDays:parseInt(textRange(row,512,544).replace(/\D/g,''),10)||0,entryWeight:number(textRange(row,412,441)),gmd:number(textRange(row,544,572)),estimatedWeight:number(textRange(row,572,604)),exitWeight:number(textRange(row,604,631)),estimatedExit:exitMatch?dateIso(exitMatch[0]):'',consumption:number(textRange(row,680,715)),kgCabMS:number(textRange(row,715,748)),kgCabMN:number(textRange(row,748,778)),pv:number(textRange(row,778,820))});
  });return out;
}
async function importPdf(file){
  showToast('Lendo o relatório Bovino.OS...');var pdfjs=window.pdfjsLib;if(!pdfjs)throw new Error('Leitor de PDF indisponível.');pdfjs.GlobalWorkerOptions.workerSrc='vendor/pdf.worker.min.js';var doc=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,context={line:'',reportDate:''},lots=[];
  for(var n=1;n<=doc.numPages;n++){var page=await doc.getPage(n),tc=await page.getTextContent();if(n===1){var header=tc.items.map(function(i){return String(i.str||'').trim();}).join(' ');if(!/Bovino\.OS/i.test(header)||!/Tipo\s+de\s+entrada/i.test(header))throw new Error('Use o relatório Bovino.OS de Lotes Ativos com a coluna Tipo de entrada.');}lots=lots.concat(parsePage(tc.items,context));}
  if(!lots.length)throw new Error('Nenhum lote dos currais A a P foi reconhecido.');state.lots=lots;state.reportDate=context.reportDate;state.importedAt=new Date().toISOString();save();selectedKey='';render();showToast(lots.length+' lotes e '+int(sum(lots,'quantity'))+' animais atualizados. As anotações foram preservadas.');
}
function sum(rows,key){return rows.reduce(function(s,r){return s+Number(typeof key==='function'?key(r):r[key]||0);},0);}
function kpi(label,value,sub,cls,action){var tag=action?'button':'div';return '<'+tag+' class="kpi '+(cls||'')+(action?' clickable':'')+'"'+(action?' data-kpi="'+action+'" type="button"':'')+'><span>'+label+'</span><strong>'+value+'</strong><small>'+sub+(action?' · toque para filtrar':'')+'</small></'+tag+'>';}
function filtered(){var q=norm(el('searchFilter').value),line=el('lineFilter').value,diet=el('dietFilter').value,type=el('typeFilter').value,note=el('noteFilter').value,min=inputNumber(el('consMin').value),max=inputNumber(el('consMax').value),daysMin=inputNumber(el('daysMin').value),daysMax=inputNumber(el('daysMax').value);return state.lots.filter(function(l){var notes=activeNotes(l).length,search=!q||norm(l.name+' '+l.pen+' '+l.line+' '+l.category).indexOf(q)>=0;return search&&(!line||l.line===line)&&(!diet||norm(l.diet)===diet)&&(!type||l.type===type)&&(!note||(note==='active'?notes>0:notes===0))&&(min===null||l.pv>=min)&&(max===null||l.pv<=max)&&(daysMin===null||l.days>=daysMin)&&(daysMax===null||l.days<=daysMax);});}
function fillFilters(){var line=el('lineFilter').value,diet=el('dietFilter').value,lines=Array.from(new Set(state.lots.map(function(l){return l.line;}))).filter(Boolean).sort(),diets=Array.from(new Set(state.lots.map(function(l){return norm(l.diet);}))).filter(Boolean).sort();el('lineFilter').innerHTML='<option value="">Todas</option>'+lines.map(function(x){return '<option value="'+x+'">Linha '+x+'</option>';}).join('');el('dietFilter').innerHTML='<option value="">Todas</option>'+diets.map(function(x){return '<option value="'+esc(x)+'">'+esc(x)+'</option>';}).join('');el('lineFilter').value=line;el('dietFilter').value=diet;}
function render(){fillFilters();var rows=filtered(),term=state.lots.filter(function(l){return norm(l.diet)==='TERMINACAO';}),notes=state.notes.filter(function(n){return n.status==='active';});el('positionLabel').textContent=state.reportDate?'Posição em '+dateBr(state.reportDate)+' · atualizado '+new Date(state.importedAt).toLocaleString('pt-BR'):'Nenhum relatório importado';el('summary').innerHTML=kpi('Animais atuais',int(sum(state.lots,'quantity')),state.lots.length+' lotes')+kpi('Em terminação',int(sum(term,'quantity')),term.length+' lotes','gold','diet-term')+kpi('Currais ocupados',new Set(state.lots.map(function(l){return l.pen;})).size,'linhas A a P')+kpi('Consumo abaixo de 1,8%',int(sum(state.lots.filter(function(l){return l.pv<1.8;}),'quantity')),'animais para observar','red','cons-low')+kpi('Anotações ativas',int(notes.length),'acompanhamentos pendentes','blue','notes-active');el('resultCount').textContent=rows.length+' '+(rows.length===1?'curral':'currais');el('resultAnimals').textContent=int(sum(rows,'quantity'))+' animais';el('penMap').innerHTML=rows.length?rows.sort(function(a,b){return (a.line+a.pen).localeCompare(b.line+b.pen,undefined,{numeric:true});}).map(card).join(''):'<div class="empty">Nenhum curral corresponde aos filtros escolhidos.</div>';el('lineBreakdown').innerHTML=lineBreakdown(rows);updateSelectionBar();}
function lineBreakdown(rows){if(!rows.length)return '';var byLine={};rows.forEach(function(l){var b=byLine[l.line]||(byLine[l.line]={pens:0,animals:0});b.pens++;b.animals+=Number(l.quantity)||0;});return Object.keys(byLine).sort().map(function(k){var b=byLine[k];return '<span class="line-chip">Linha '+esc(k)+'<b>'+int(b.pens)+' '+(b.pens===1?'curral':'currais')+' · '+int(b.animals)+' animais</b></span>';}).join('');}
function selectedLots(){var valid=new Set(state.lots.map(lotKey));Array.from(selected).forEach(function(k){if(!valid.has(k))selected.delete(k);});return state.lots.filter(function(l){return selected.has(lotKey(l));});}
function updateSelectionBar(){var lots=selectedLots().sort(function(a,b){return (a.line+a.pen).localeCompare(b.line+b.pen,undefined,{numeric:true});}),bar=el('selectionBar');if(!lots.length){bar.hidden=true;return;}bar.hidden=false;el('selectionSummary').textContent=lots.length+' lote'+(lots.length===1?'':'s')+' selecionado'+(lots.length===1?'':'s')+' · '+int(sum(lots,'quantity'))+' animais';el('selectionChips').innerHTML=lots.map(function(l){return '<span class="selection-chip">'+esc(l.pen)+' · '+esc(l.name)+'<button type="button" data-deselect="'+esc(lotKey(l))+'" title="Remover da seleção" aria-label="Remover">×</button></span>';}).join('');}
function card(l){var notes=activeNotes(l),alert=l.pv<1.8||l.pv>2.5,key=lotKey(l),checked=selected.has(key);return '<div class="pen-card '+l.type+(alert?' alert':'')+(notes.length?' has-note':'')+(checked?' selected':'')+'" data-lot="'+esc(key)+'" tabindex="0" role="button"><label class="pen-select" title="Selecionar para exportar" onclick="event.stopPropagation()"><input type="checkbox" data-select="'+esc(key)+'"'+(checked?' checked':'')+'></label><div class="pen-top"><span class="pen-code">'+esc(l.pen)+'</span><span class="pen-type">'+(l.type==='own'?'Próprio':'Boitel')+'</span></div><strong class="lot-name">'+esc(l.name)+'</strong>'+(l.category?'<span class="pen-owner" title="Categoria / proprietário">'+esc(l.category)+'</span>':'')+'<div class="pen-qty">'+int(l.quantity)+' <small>animais</small></div><div class="pen-meta"><span>Dieta<b>'+esc(l.diet)+'</b></span><span>Consumo %PV<b>'+decimal(l.pv,2)+'%</b></span><span>Dias conf.<b>'+int(l.days)+'</b></span><span>Consumo MS (kg/cab)<b>'+decimal(l.kgCabMS,2)+' kg</b></span></div>'+(notes.length?'<div class="note-badge">● '+notes.length+' anotação'+(notes.length>1?'ões':'')+' ativa'+(notes.length>1?'s':'')+'</div>':'')+'</div>';}
function currentLot(){return state.lots.find(function(l){return lotKey(l)===selectedKey;});}
function detailItem(label,value){return '<div class="detail-item"><span>'+label+'</span><strong>'+esc(value==null||value===''?'—':value)+'</strong></div>';}
function renderDetail(){var l=currentLot();if(!l){el('drawer').hidden=true;return;}el('detailTitle').textContent='Curral '+l.pen+' · '+l.name;var lk=lotKey(l),related=state.notes.filter(function(n){return (n.scope==='lot'&&n.targetKey===lk)||(n.scope==='pen'&&n.targetKey===l.pen);}).sort(function(a,b){return b.createdAt.localeCompare(a.createdAt);});el('detailBody').innerHTML='<div class="detail-hero"><div class="detail-box"><span>Animais</span><strong>'+int(l.quantity)+'</strong></div><div class="detail-box"><span>Dieta</span><strong>'+esc(l.diet)+'</strong></div><div class="detail-box"><span>Consumo %PV</span><strong>'+decimal(l.pv,2)+'%</strong></div><div class="detail-box"><span>Dias confinamento</span><strong>'+int(l.days)+'</strong></div></div><div class="detail-grid">'+detailItem('Categoria / dono',l.category)+detailItem('Tipo',l.type==='own'?'Próprio':'Boitel')+detailItem('Raça',l.breed)+detailItem('Entrada',dateBr(l.entryDate))+detailItem('Peso entrada',decimal(l.entryWeight,1)+' kg')+detailItem('Peso estimado',decimal(l.estimatedWeight,1)+' kg')+detailItem('Peso de saída',decimal(l.exitWeight,1)+' kg')+detailItem('Saída estimada',dateBr(l.estimatedExit))+detailItem('GMD',decimal(l.gmd,2)+' kg/dia')+detailItem('Consumo MS por cabeça',decimal(l.kgCabMS,2)+' kg/dia')+detailItem('Consumo MN por cabeça',decimal(l.kgCabMN,2)+' kg/dia')+detailItem('Consumo MN total da baia',decimal(l.consumption,2)+' ton/dia')+detailItem('Dias de trato',int(l.treatmentDays))+detailItem('Mortes',int(l.deaths))+'</div><div class="notes-layout"><form class="note-form" id="noteForm"><h3>Nova anotação</h3><label>A anotação acompanha<select name="scope"><option value="lot">Este lote, mesmo se mudar de curral</option><option value="pen">Este curral</option></select></label><label>Anotação<textarea name="text" required placeholder="Registre o que foi observado e o que precisa ser acompanhado."></textarea></label><div class="note-actions"><button class="btn primary" type="submit">Salvar anotação</button><button class="btn secondary" type="button" id="closePenNotes">Concluir anotações do curral</button></div></form><section class="notes-panel"><h3>Histórico</h3>'+(related.length?related.map(noteCard).join(''):'<div class="empty">Nenhuma anotação registrada.</div>')+'</section></div>';el('noteForm').onsubmit=addNote;el('closePenNotes').onclick=closePenNotes;}
function noteCard(n){return '<article class="note-card '+(n.status==='closed'?'closed':'')+'">'+(n.status==='active'?'<button data-close-note="'+n.id+'">Concluir</button>':'')+'<small>'+(n.scope==='lot'?'LOTE':'CURRAL')+' · '+new Date(n.createdAt).toLocaleString('pt-BR')+(n.closedAt?' · concluída '+new Date(n.closedAt).toLocaleString('pt-BR'):'')+'</small><p>'+esc(n.text)+'</p></article>';}
function addNote(e){e.preventDefault();var l=currentLot(),fd=new FormData(e.target),scope=fd.get('scope'),text=String(fd.get('text')||'').trim();if(!l||!text)return;state.notes.push({id:uid(),scope:scope,targetKey:scope==='lot'?lotKey(l):l.pen,lotName:l.name,pen:l.pen,text:text,status:'active',createdAt:new Date().toISOString(),closedAt:''});save();render();renderDetail();showToast('Anotação salva.');}
function conclude(id){var n=state.notes.find(function(x){return x.id===id;});if(!n)return;n.status='closed';n.closedAt=new Date().toISOString();save();render();renderDetail();showToast('Anotação concluída e mantida no histórico.');}
function closePenNotes(){var l=currentLot(),list=state.notes.filter(function(n){return n.status==='active'&&n.scope==='pen'&&n.targetKey===l.pen;});if(!list.length){showToast('Este curral não possui anotação ativa.');return;}if(!confirm('Concluir as '+list.length+' anotações ativas deste curral? Elas continuarão no histórico.'))return;list.forEach(function(n){n.status='closed';n.closedAt=new Date().toISOString();});save();render();renderDetail();showToast('Anotações do curral concluídas.');}
function clearFilters(){['searchFilter','lineFilter','dietFilter','typeFilter','noteFilter','consMin','consMax','daysMin','daysMax'].forEach(function(id){el(id).value='';});render();}
function download(name,text,mime){var b=new Blob([text],{type:mime||'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u);},500);}
function backup(){download('Recorrida_Confinamento_'+tsFile(new Date())+'.json',JSON.stringify({tipo:'recorrida_confinamento',exportadoEm:new Date().toISOString(),state:state},null,2));showToast('Cópia de segurança salva.');}
function csvField(v){var s=String(v==null?'':v);return /[;"\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function exportRows(){return selectedLots().sort(function(a,b){return (a.line+a.pen).localeCompare(b.line+b.pen,undefined,{numeric:true});});}
function exportPrint(){var lots=exportRows();if(!lots.length){showToast('Selecione ao menos um lote para exportar.');return;}
  var rows=lots.map(function(l){return '<tr><td>'+esc(l.line)+'</td><td>'+esc(l.pen)+'</td><td>'+esc(l.name)+'</td><td>'+esc(l.category||'')+'</td><td>'+(l.type==='own'?'Próprio':'Boitel')+'</td><td>'+esc(l.breed||'')+'</td><td>'+esc(l.diet)+'</td><td>'+int(l.quantity)+'</td><td>'+decimal(l.pv,2)+'%</td><td>'+int(l.days)+'</td><td>'+decimal(l.estimatedWeight,1)+'</td><td>'+dateBr(l.estimatedExit)+'</td></tr>';}).join('');
  el('printArea').innerHTML='<h1>Recorrida do Confinamento — Lotes selecionados</h1><p>Posição em '+dateBr(state.reportDate)+' · gerado em '+new Date().toLocaleString('pt-BR')+' · '+lots.length+' lote'+(lots.length===1?'':'s')+' · '+int(sum(lots,'quantity'))+' animais</p><table><thead><tr><th>Linha</th><th>Curral</th><th>Lote</th><th>Categoria/Dono</th><th>Tipo</th><th>Raça</th><th>Dieta</th><th>Animais</th><th>Consumo %PV</th><th>Dias conf.</th><th>Peso est. (kg)</th><th>Saída estimada</th></tr></thead><tbody>'+rows+'</tbody></table>';
  window.print();
}
function exportCsv(){var lots=exportRows();if(!lots.length){showToast('Selecione ao menos um lote para exportar.');return;}
  var head=['Linha','Curral','Lote','Categoria/Dono','Tipo','Raça','Dieta','Animais','Consumo %PV','Dias confinamento','Peso estimado (kg)','Saída estimada'],rows=lots.map(function(l){return [l.line,l.pen,l.name,l.category||'',l.type==='own'?'Próprio':'Boitel',l.breed||'',l.diet,l.quantity,decimal(l.pv,2),l.days,decimal(l.estimatedWeight,1),dateBr(l.estimatedExit)].map(csvField).join(';');});
  download('Lotes_selecionados_'+tsFile(new Date())+'.csv','﻿'+[head.join(';')].concat(rows).join('\r\n'),'text/csv');
  showToast(lots.length+' lote'+(lots.length===1?'':'s')+' exportado'+(lots.length===1?'':'s')+' em CSV.');
}
function mergeNotes(current,incoming){var map={};current.forEach(function(n){map[n.id]=n;});incoming.forEach(function(n){var ex=map[n.id];if(!ex)map[n.id]=n;else if(n.status==='closed'&&ex.status!=='closed')map[n.id]=n;});return Object.keys(map).map(function(k){return map[k];});}
async function restore(file){
  try{
    var d=JSON.parse(await file.text()),s=d.state||d;
    if(!Array.isArray(s.lots)||!Array.isArray(s.notes))throw new Error();
    var incomingNewer=!!s.importedAt&&(!state.importedAt||s.importedAt>state.importedAt),mergedNotes=mergeNotes(state.notes,s.notes),addedNotes=mergedNotes.length-state.notes.length;
    if(!confirm('Mesclar esta cópia com os dados deste aparelho?\n'+(incomingNewer?'A posição de lotes será atualizada para a mais recente (do arquivo importado).':'A posição de lotes deste aparelho já é a mais recente e será mantida.')+'\nAs anotações dos dois arquivos serão combinadas, sem duplicar e sem apagar nada.'))return;
    state=Object.assign(defaults(),{version:state.version,lots:incomingNewer?s.lots:state.lots,reportDate:incomingNewer?s.reportDate:state.reportDate,importedAt:incomingNewer?s.importedAt:state.importedAt,notes:mergedNotes});
    save();render();showToast('Cópia mesclada'+(addedNotes>0?': '+addedNotes+' anotação(ões) nova(s) incorporada(s).':'.'));
  }catch(e){showToast('Arquivo de cópia inválido.');}
}
function bind(){el('importBtn').onclick=function(){el('pdfInput').click();};el('pdfInput').onchange=async function(){var f=this.files&&this.files[0];if(!f)return;try{await importPdf(f);}catch(e){console.error(e);showToast(e.message||'Não foi possível importar o PDF.');}finally{this.value='';}};el('backupBtn').onclick=backup;el('restoreBtn').onclick=function(){el('restoreInput').click();};el('restoreInput').onchange=function(){var f=this.files&&this.files[0];if(f)restore(f);this.value='';};['searchFilter','lineFilter','dietFilter','typeFilter','noteFilter','consMin','consMax','daysMin','daysMax'].forEach(function(id){el(id).addEventListener(id==='searchFilter'||id.indexOf('cons')===0||id.indexOf('days')===0?'input':'change',render);});el('clearFilters').onclick=clearFilters;document.querySelector('.quick-filters').onclick=function(e){var b=e.target.closest('button');if(!b)return;if(b.dataset.cons==='low'){el('consMin').value='';el('consMax').value='1.8';}if(b.dataset.cons==='high'){el('consMin').value='2.5';el('consMax').value='';}if(b.dataset.diet)el('dietFilter').value=b.dataset.diet;if(b.dataset.notes)el('noteFilter').value=b.dataset.notes;if(b.dataset.days){var r=b.dataset.days.split('-');el('daysMin').value=r[0];el('daysMax').value=r[1];}render();};el('summary').onclick=function(e){var b=e.target.closest('[data-kpi]');if(!b)return;if(b.dataset.kpi==='cons-low'){el('consMin').value='';el('consMax').value='1.8';}if(b.dataset.kpi==='diet-term'){el('dietFilter').value='TERMINACAO';}if(b.dataset.kpi==='notes-active'){el('noteFilter').value='active';}render();};el('penMap').onclick=function(e){if(e.target.closest('.pen-select'))return;var b=e.target.closest('[data-lot]');if(!b)return;selectedKey=b.dataset.lot;renderDetail();el('drawer').hidden=false;};el('penMap').addEventListener('change',function(e){var cb=e.target.closest('[data-select]');if(!cb)return;if(cb.checked)selected.add(cb.dataset.select);else selected.delete(cb.dataset.select);render();});el('selectAllFiltered').onclick=function(){filtered().forEach(function(l){selected.add(lotKey(l));});render();};el('clearSelection').onclick=function(){selected.clear();render();};el('selectionChips').addEventListener('click',function(e){var b=e.target.closest('[data-deselect]');if(!b)return;selected.delete(b.dataset.deselect);render();});el('exportPrintBtn').onclick=exportPrint;el('exportCsvBtn').onclick=exportCsv;el('closeDrawer').onclick=function(){el('drawer').hidden=true;};el('drawer').onclick=function(e){if(e.target===this)this.hidden=true;};el('detailBody').onclick=function(e){var b=e.target.closest('[data-close-note]');if(b)conclude(b.dataset.closeNote);};document.addEventListener('keydown',function(e){if(e.key==='Escape')el('drawer').hidden=true;});}
document.addEventListener('DOMContentLoaded',function(){bind();render();if('serviceWorker' in navigator&&location.protocol.indexOf('http')===0)navigator.serviceWorker.register('./sw.js').catch(function(){});});
})();
